model:
  class_path: model.ResNet18
  init_args:
    n_out: 5
    lr: 5e-4
data:
  class_path: dataset.PROVABGSDataset
  init_args:
    dataset_path: '/mnt/home/lparker/ceph/decals_provabgs'
    modality: 'image'
    batch_size: 128
    val_size: 0.2
    range_compression_factor: 0.01
trainer:
  max_epochs: 30
  accelerator: gpu
  callbacks:
  - class_path: utils.R2ScoreCallback
